[workspace]
repository = "github.com/embedr/ai_pendant_recorder"
pcb-version = "0.4"

[board]
name = "ai_pendant_recorder"
path = "ai_pendant_recorder.zen"
description = "Embedr electronics workspace"

[dependencies]
"github.com/embedr/ai_pendant_recorder/components/ck-js202011aqn" = "0.1.0"
"github.com/embedr/ai_pendant_recorder/components/jst-b2b-ph-k-s" = "0.1.0"
"github.com/embedr/ai_pendant_recorder/components/jst-bm02b-srss-tb" = "0.1.0"
"github.com/embedr/ai_pendant_recorder/components/pts841gksmtr" = "0.1.0"
"github.com/embedr/ai_pendant_recorder/components/seeed-xiao-esp32s3-sense" = "0.1.0"
